#undef __ATTR_SAL
#undef _SAL_VERSION
#undef _USE_DECLSPECS_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_DECLSPECS_FOR_SAL
#undef _USE_DECLSPECS_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _USE_DECLSPECS_FOR_SAL
#undef _USE_ATTRIBUTES_FOR_SAL
#undef _SAL1_Source_
#undef _SAL1_1_Source_
#undef _SAL1_2_Source_
#undef _SAL2_Source_
#undef _SAL1_Source_
#undef _SAL1_1_Source_
#undef _SAL1_2_Source_
#undef _SAL2_Source_
#undef _At_
#undef _At_buffer_
#undef _When_
#undef _Group_
#undef _GrouP_
#undef _Success_
#undef _Return_type_success_
#undef _On_failure_
#undef _Always_
#undef _Use_decl_annotations_
#undef _Notref_
#undef _Pre_defensive_
#undef _Post_defensive_
#undef _In_defensive_
#undef _Out_defensive_
#undef _Inout_defensive_
#undef _Reserved_
#undef _Const_
#undef _In_
#undef _In_opt_
#undef _In_z_
#undef _In_opt_z_
#undef _In_reads_
#undef _In_reads_opt_
#undef _In_reads_bytes_
#undef _In_reads_bytes_opt_
#undef _In_reads_z_
#undef _In_reads_opt_z_
#undef _In_reads_or_z_
#undef _In_reads_or_z_opt_
#undef _In_reads_to_ptr_
#undef _In_reads_to_ptr_opt_
#undef _In_reads_to_ptr_z_
#undef _In_reads_to_ptr_opt_z_
#undef _Out_
#undef _Out_opt_
#undef _Out_writes_
#undef _Out_writes_opt_
#undef _Out_writes_bytes_
#undef _Out_writes_bytes_opt_
#undef _Out_writes_z_
#undef _Out_writes_opt_z_
#undef _Out_writes_to_
#undef _Out_writes_to_opt_
#undef _Out_writes_all_
#undef _Out_writes_all_opt_
#undef _Out_writes_bytes_to_
#undef _Out_writes_bytes_to_opt_
#undef _Out_writes_bytes_all_
#undef _Out_writes_bytes_all_opt_
#undef _Out_writes_to_ptr_
#undef _Out_writes_to_ptr_opt_
#undef _Out_writes_to_ptr_z_
#undef _Out_writes_to_ptr_opt_z_
#undef _Inout_
#undef _Inout_opt_
#undef _Inout_z_
#undef _Inout_opt_z_
#undef _Inout_updates_
#undef _Inout_updates_opt_
#undef _Inout_updates_z_
#undef _Inout_updates_opt_z_
#undef _Inout_updates_to_
#undef _Inout_updates_to_opt_
#undef _Inout_updates_all_
#undef _Inout_updates_all_opt_
#undef _Inout_updates_bytes_
#undef _Inout_updates_bytes_opt_
#undef _Inout_updates_bytes_to_
#undef _Inout_updates_bytes_to_opt_
#undef _Inout_updates_bytes_all_
#undef _Inout_updates_bytes_all_opt_
#undef _Outptr_
#undef _Outptr_result_maybenull_
#undef _Outptr_opt_
#undef _Outptr_opt_result_maybenull_
#undef _Outptr_result_z_
#undef _Outptr_opt_result_z_
#undef _Outptr_result_maybenull_z_
#undef _Outptr_opt_result_maybenull_z_
#undef _Outptr_result_nullonfailure_
#undef _Outptr_opt_result_nullonfailure_
#undef _COM_Outptr_
#undef _COM_Outptr_result_maybenull_
#undef _COM_Outptr_opt_
#undef _COM_Outptr_opt_result_maybenull_
#undef _Outptr_result_buffer_
#undef _Outptr_opt_result_buffer_
#undef _Outptr_result_buffer_to_
#undef _Outptr_opt_result_buffer_to_
#undef _Outptr_result_buffer_all_
#undef _Outptr_opt_result_buffer_all_
#undef _Outptr_result_buffer_maybenull_
#undef _Outptr_opt_result_buffer_maybenull_
#undef _Outptr_result_buffer_to_maybenull_
#undef _Outptr_opt_result_buffer_to_maybenull_
#undef _Outptr_result_buffer_all_maybenull_
#undef _Outptr_opt_result_buffer_all_maybenull_
#undef _Outptr_result_bytebuffer_
#undef _Outptr_opt_result_bytebuffer_
#undef _Outptr_result_bytebuffer_to_
#undef _Outptr_opt_result_bytebuffer_to_
#undef _Outptr_result_bytebuffer_all_
#undef _Outptr_opt_result_bytebuffer_all_
#undef _Outptr_result_bytebuffer_maybenull_
#undef _Outptr_opt_result_bytebuffer_maybenull_
#undef _Outptr_result_bytebuffer_to_maybenull_
#undef _Outptr_opt_result_bytebuffer_to_maybenull_
#undef _Outptr_result_bytebuffer_all_maybenull_
#undef _Outptr_opt_result_bytebuffer_all_maybenull_
#undef _Outref_
#undef _Outref_result_maybenull_
#undef _Outref_result_buffer_
#undef _Outref_result_bytebuffer_
#undef _Outref_result_buffer_to_
#undef _Outref_result_bytebuffer_to_
#undef _Outref_result_buffer_all_
#undef _Outref_result_bytebuffer_all_
#undef _Outref_result_buffer_maybenull_
#undef _Outref_result_bytebuffer_maybenull_
#undef _Outref_result_buffer_to_maybenull_
#undef _Outref_result_bytebuffer_to_maybenull_
#undef _Outref_result_buffer_all_maybenull_
#undef _Outref_result_bytebuffer_all_maybenull_
#undef _Outref_result_nullonfailure_
#undef _Result_nullonfailure_
#undef _Result_zeroonfailure_
#undef _Ret_z_
#undef _Ret_maybenull_z_
#undef _Ret_notnull_
#undef _Ret_maybenull_
#undef _Ret_null_
#undef _Ret_valid_
#undef _Ret_writes_
#undef _Ret_writes_z_
#undef _Ret_writes_bytes_
#undef _Ret_writes_maybenull_
#undef _Ret_writes_maybenull_z_
#undef _Ret_writes_bytes_maybenull_
#undef _Ret_writes_to_
#undef _Ret_writes_bytes_to_
#undef _Ret_writes_to_maybenull_
#undef _Ret_writes_bytes_to_maybenull_
#undef _Points_to_data_
#undef _Literal_
#undef _Notliteral_
#undef _Check_return_
#undef _Must_inspect_result_
#undef _Printf_format_string_
#undef _Scanf_format_string_
#undef _Scanf_s_format_string_
#undef _Format_string_impl_
#undef _Printf_format_string_params_
#undef _Scanf_format_string_params_
#undef _Scanf_s_format_string_params_
#undef _In_range_
#undef _Out_range_
#undef _Ret_range_
#undef _Deref_in_range_
#undef _Deref_out_range_
#undef _Deref_ret_range_
#undef _Pre_equal_to_
#undef _Post_equal_to_
#undef _Unchanged_
#undef _Pre_satisfies_
#undef _Post_satisfies_
#undef _Struct_size_bytes_
#undef _Field_size_
#undef _Field_size_opt_
#undef _Field_size_part_
#undef _Field_size_part_opt_
#undef _Field_size_full_
#undef _Field_size_full_opt_
#undef _Field_size_bytes_
#undef _Field_size_bytes_opt_
#undef _Field_size_bytes_part_
#undef _Field_size_bytes_part_opt_
#undef _Field_size_bytes_full_
#undef _Field_size_bytes_full_opt_
#undef _Field_z_
#undef _Field_range_
#undef _Pre_
#undef _Post_
#undef _Valid_
#undef _Notvalid_
#undef _Maybevalid_
#undef _Readable_bytes_
#undef _Readable_elements_
#undef _Writable_bytes_
#undef _Writable_elements_
#undef _Null_terminated_
#undef _NullNull_terminated_
#undef _Pre_readable_size_
#undef _Pre_writable_size_
#undef _Pre_readable_byte_size_
#undef _Pre_writable_byte_size_
#undef _Post_readable_size_
#undef _Post_writable_size_
#undef _Post_readable_byte_size_
#undef _Post_writable_byte_size_
#undef _Null_
#undef _Notnull_
#undef _Maybenull_
#undef _Pre_z_
#undef _Pre_valid_
#undef _Pre_opt_valid_
#undef _Pre_invalid_
#undef _Pre_unknown_
#undef _Pre_notnull_
#undef _Pre_maybenull_
#undef _Pre_null_
#undef _Post_z_
#undef _Post_valid_
#undef _Post_invalid_
#undef _Post_ptr_invalid_
#undef _Post_notnull_
#undef _Post_null_
#undef _Post_maybenull_
#undef _Prepost_z_
#undef _In_count_
#undef _In_opt_count_
#undef _In_bytecount_
#undef _In_opt_bytecount_
#undef _In_count_c_
#undef _In_opt_count_c_
#undef _In_bytecount_c_
#undef _In_opt_bytecount_c_
#undef _In_z_count_
#undef _In_opt_z_count_
#undef _In_z_bytecount_
#undef _In_opt_z_bytecount_
#undef _In_z_count_c_
#undef _In_opt_z_count_c_
#undef _In_z_bytecount_c_
#undef _In_opt_z_bytecount_c_
#undef _In_ptrdiff_count_
#undef _In_opt_ptrdiff_count_
#undef _In_count_x_
#undef _In_opt_count_x_
#undef _In_bytecount_x_
#undef _In_opt_bytecount_x_
#undef _Out_cap_
#undef _Out_opt_cap_
#undef _Out_bytecap_
#undef _Out_opt_bytecap_
#undef _Out_cap_c_
#undef _Out_opt_cap_c_
#undef _Out_bytecap_c_
#undef _Out_opt_bytecap_c_
#undef _Out_cap_m_
#undef _Out_opt_cap_m_
#undef _Out_z_cap_m_
#undef _Out_opt_z_cap_m_
#undef _Out_ptrdiff_cap_
#undef _Out_opt_ptrdiff_cap_
#undef _Out_cap_x_
#undef _Out_opt_cap_x_
#undef _Out_bytecap_x_
#undef _Out_opt_bytecap_x_
#undef _Out_z_cap_
#undef _Out_opt_z_cap_
#undef _Out_z_bytecap_
#undef _Out_opt_z_bytecap_
#undef _Out_z_cap_c_
#undef _Out_opt_z_cap_c_
#undef _Out_z_bytecap_c_
#undef _Out_opt_z_bytecap_c_
#undef _Out_z_cap_x_
#undef _Out_opt_z_cap_x_
#undef _Out_z_bytecap_x_
#undef _Out_opt_z_bytecap_x_
#undef _Out_cap_post_count_
#undef _Out_opt_cap_post_count_
#undef _Out_bytecap_post_bytecount_
#undef _Out_opt_bytecap_post_bytecount_
#undef _Out_z_cap_post_count_
#undef _Out_opt_z_cap_post_count_
#undef _Out_z_bytecap_post_bytecount_
#undef _Out_opt_z_bytecap_post_bytecount_
#undef _Out_capcount_
#undef _Out_opt_capcount_
#undef _Out_bytecapcount_
#undef _Out_opt_bytecapcount_
#undef _Out_capcount_x_
#undef _Out_opt_capcount_x_
#undef _Out_bytecapcount_x_
#undef _Out_opt_bytecapcount_x_
#undef _Out_z_capcount_
#undef _Out_opt_z_capcount_
#undef _Out_z_bytecapcount_
#undef _Out_opt_z_bytecapcount_
#undef _Inout_count_
#undef _Inout_opt_count_
#undef _Inout_bytecount_
#undef _Inout_opt_bytecount_
#undef _Inout_count_c_
#undef _Inout_opt_count_c_
#undef _Inout_bytecount_c_
#undef _Inout_opt_bytecount_c_
#undef _Inout_z_count_
#undef _Inout_opt_z_count_
#undef _Inout_z_bytecount_
#undef _Inout_opt_z_bytecount_
#undef _Inout_z_count_c_
#undef _Inout_opt_z_count_c_
#undef _Inout_z_bytecount_c_
#undef _Inout_opt_z_bytecount_c_
#undef _Inout_ptrdiff_count_
#undef _Inout_opt_ptrdiff_count_
#undef _Inout_count_x_
#undef _Inout_opt_count_x_
#undef _Inout_bytecount_x_
#undef _Inout_opt_bytecount_x_
#undef _Inout_cap_
#undef _Inout_opt_cap_
#undef _Inout_bytecap_
#undef _Inout_opt_bytecap_
#undef _Inout_cap_c_
#undef _Inout_opt_cap_c_
#undef _Inout_bytecap_c_
#undef _Inout_opt_bytecap_c_
#undef _Inout_cap_x_
#undef _Inout_opt_cap_x_
#undef _Inout_bytecap_x_
#undef _Inout_opt_bytecap_x_
#undef _Inout_z_cap_
#undef _Inout_opt_z_cap_
#undef _Inout_z_bytecap_
#undef _Inout_opt_z_bytecap_
#undef _Inout_z_cap_c_
#undef _Inout_opt_z_cap_c_
#undef _Inout_z_bytecap_c_
#undef _Inout_opt_z_bytecap_c_
#undef _Inout_z_cap_x_
#undef _Inout_opt_z_cap_x_
#undef _Inout_z_bytecap_x_
#undef _Inout_opt_z_bytecap_x_
#undef _Ret_
#undef _Ret_opt_
#undef _In_bound_
#undef _Out_bound_
#undef _Ret_bound_
#undef _Deref_in_bound_
#undef _Deref_out_bound_
#undef _Deref_inout_bound_
#undef _Deref_ret_bound_
#undef _Deref_out_
#undef _Deref_out_opt_
#undef _Deref_opt_out_
#undef _Deref_opt_out_opt_
#undef _Deref_out_z_
#undef _Deref_out_opt_z_
#undef _Deref_opt_out_z_
#undef _Deref_opt_out_opt_z_
#undef _Deref_pre_z_
#undef _Deref_pre_opt_z_
#undef _Deref_pre_cap_
#undef _Deref_pre_opt_cap_
#undef _Deref_pre_bytecap_
#undef _Deref_pre_opt_bytecap_
#undef _Deref_pre_cap_c_
#undef _Deref_pre_opt_cap_c_
#undef _Deref_pre_bytecap_c_
#undef _Deref_pre_opt_bytecap_c_
#undef _Deref_pre_cap_x_
#undef _Deref_pre_opt_cap_x_
#undef _Deref_pre_bytecap_x_
#undef _Deref_pre_opt_bytecap_x_
#undef _Deref_pre_z_cap_
#undef _Deref_pre_opt_z_cap_
#undef _Deref_pre_z_bytecap_
#undef _Deref_pre_opt_z_bytecap_
#undef _Deref_pre_z_cap_c_
#undef _Deref_pre_opt_z_cap_c_
#undef _Deref_pre_z_bytecap_c_
#undef _Deref_pre_opt_z_bytecap_c_
#undef _Deref_pre_z_cap_x_
#undef _Deref_pre_opt_z_cap_x_
#undef _Deref_pre_z_bytecap_x_
#undef _Deref_pre_opt_z_bytecap_x_
#undef _Deref_pre_valid_cap_
#undef _Deref_pre_opt_valid_cap_
#undef _Deref_pre_valid_bytecap_
#undef _Deref_pre_opt_valid_bytecap_
#undef _Deref_pre_valid_cap_c_
#undef _Deref_pre_opt_valid_cap_c_
#undef _Deref_pre_valid_bytecap_c_
#undef _Deref_pre_opt_valid_bytecap_c_
#undef _Deref_pre_valid_cap_x_
#undef _Deref_pre_opt_valid_cap_x_
#undef _Deref_pre_valid_bytecap_x_
#undef _Deref_pre_opt_valid_bytecap_x_
#undef _Deref_pre_count_
#undef _Deref_pre_opt_count_
#undef _Deref_pre_bytecount_
#undef _Deref_pre_opt_bytecount_
#undef _Deref_pre_count_c_
#undef _Deref_pre_opt_count_c_
#undef _Deref_pre_bytecount_c_
#undef _Deref_pre_opt_bytecount_c_
#undef _Deref_pre_count_x_
#undef _Deref_pre_opt_count_x_
#undef _Deref_pre_bytecount_x_
#undef _Deref_pre_opt_bytecount_x_
#undef _Deref_pre_valid_
#undef _Deref_pre_opt_valid_
#undef _Deref_pre_invalid_
#undef _Deref_pre_notnull_
#undef _Deref_pre_maybenull_
#undef _Deref_pre_null_
#undef _Deref_pre_readonly_
#undef _Deref_pre_writeonly_
#undef _Deref_post_z_
#undef _Deref_post_opt_z_
#undef _Deref_post_cap_
#undef _Deref_post_opt_cap_
#undef _Deref_post_bytecap_
#undef _Deref_post_opt_bytecap_
#undef _Deref_post_cap_c_
#undef _Deref_post_opt_cap_c_
#undef _Deref_post_bytecap_c_
#undef _Deref_post_opt_bytecap_c_
#undef _Deref_post_cap_x_
#undef _Deref_post_opt_cap_x_
#undef _Deref_post_bytecap_x_
#undef _Deref_post_opt_bytecap_x_
#undef _Deref_post_z_cap_
#undef _Deref_post_opt_z_cap_
#undef _Deref_post_z_bytecap_
#undef _Deref_post_opt_z_bytecap_
#undef _Deref_post_z_cap_c_
#undef _Deref_post_opt_z_cap_c_
#undef _Deref_post_z_bytecap_c_
#undef _Deref_post_opt_z_bytecap_c_
#undef _Deref_post_z_cap_x_
#undef _Deref_post_opt_z_cap_x_
#undef _Deref_post_z_bytecap_x_
#undef _Deref_post_opt_z_bytecap_x_
#undef _Deref_post_valid_cap_
#undef _Deref_post_opt_valid_cap_
#undef _Deref_post_valid_bytecap_
#undef _Deref_post_opt_valid_bytecap_
#undef _Deref_post_valid_cap_c_
#undef _Deref_post_opt_valid_cap_c_
#undef _Deref_post_valid_bytecap_c_
#undef _Deref_post_opt_valid_bytecap_c_
#undef _Deref_post_valid_cap_x_
#undef _Deref_post_opt_valid_cap_x_
#undef _Deref_post_valid_bytecap_x_
#undef _Deref_post_opt_valid_bytecap_x_
#undef _Deref_post_count_
#undef _Deref_post_opt_count_
#undef _Deref_post_bytecount_
#undef _Deref_post_opt_bytecount_
#undef _Deref_post_count_c_
#undef _Deref_post_opt_count_c_
#undef _Deref_post_bytecount_c_
#undef _Deref_post_opt_bytecount_c_
#undef _Deref_post_count_x_
#undef _Deref_post_opt_count_x_
#undef _Deref_post_bytecount_x_
#undef _Deref_post_opt_bytecount_x_
#undef _Deref_post_valid_
#undef _Deref_post_opt_valid_
#undef _Deref_post_notnull_
#undef _Deref_post_maybenull_
#undef _Deref_post_null_
#undef _Deref_ret_z_
#undef _Deref_ret_opt_z_
#undef _Deref2_pre_readonly_
#undef _Ret_opt_valid_
#undef _Ret_opt_z_
#undef _Ret_cap_
#undef _Ret_opt_cap_
#undef _Ret_bytecap_
#undef _Ret_opt_bytecap_
#undef _Ret_cap_c_
#undef _Ret_opt_cap_c_
#undef _Ret_bytecap_c_
#undef _Ret_opt_bytecap_c_
#undef _Ret_cap_x_
#undef _Ret_opt_cap_x_
#undef _Ret_bytecap_x_
#undef _Ret_opt_bytecap_x_
#undef _Ret_z_cap_
#undef _Ret_opt_z_cap_
#undef _Ret_z_bytecap_
#undef _Ret_opt_z_bytecap_
#undef _Ret_count_
#undef _Ret_opt_count_
#undef _Ret_bytecount_
#undef _Ret_opt_bytecount_
#undef _Ret_count_c_
#undef _Ret_opt_count_c_
#undef _Ret_bytecount_c_
#undef _Ret_opt_bytecount_c_
#undef _Ret_count_x_
#undef _Ret_opt_count_x_
#undef _Ret_bytecount_x_
#undef _Ret_opt_bytecount_x_
#undef _Ret_z_count_
#undef _Ret_opt_z_count_
#undef _Ret_z_bytecount_
#undef _Ret_opt_z_bytecount_
#undef _Pre_opt_z_
#undef _Pre_readonly_
#undef _Pre_writeonly_
#undef _Pre_cap_
#undef _Pre_opt_cap_
#undef _Pre_bytecap_
#undef _Pre_opt_bytecap_
#undef _Pre_cap_c_
#undef _Pre_opt_cap_c_
#undef _Pre_bytecap_c_
#undef _Pre_opt_bytecap_c_
#undef _Pre_cap_c_one_
#undef _Pre_opt_cap_c_one_
#undef _Pre_cap_m_
#undef _Pre_opt_cap_m_
#undef _Pre_cap_for_
#undef _Pre_opt_cap_for_
#undef _Pre_cap_x_
#undef _Pre_opt_cap_x_
#undef _Pre_bytecap_x_
#undef _Pre_opt_bytecap_x_
#undef _Pre_ptrdiff_cap_
#undef _Pre_opt_ptrdiff_cap_
#undef _Pre_z_cap_
#undef _Pre_opt_z_cap_
#undef _Pre_z_bytecap_
#undef _Pre_opt_z_bytecap_
#undef _Pre_z_cap_c_
#undef _Pre_opt_z_cap_c_
#undef _Pre_z_bytecap_c_
#undef _Pre_opt_z_bytecap_c_
#undef _Pre_z_cap_x_
#undef _Pre_opt_z_cap_x_
#undef _Pre_z_bytecap_x_
#undef _Pre_opt_z_bytecap_x_
#undef _Pre_valid_cap_
#undef _Pre_opt_valid_cap_
#undef _Pre_valid_bytecap_
#undef _Pre_opt_valid_bytecap_
#undef _Pre_valid_cap_c_
#undef _Pre_opt_valid_cap_c_
#undef _Pre_valid_bytecap_c_
#undef _Pre_opt_valid_bytecap_c_
#undef _Pre_valid_cap_x_
#undef _Pre_opt_valid_cap_x_
#undef _Pre_valid_bytecap_x_
#undef _Pre_opt_valid_bytecap_x_
#undef _Pre_count_
#undef _Pre_opt_count_
#undef _Pre_bytecount_
#undef _Pre_opt_bytecount_
#undef _Pre_count_c_
#undef _Pre_opt_count_c_
#undef _Pre_bytecount_c_
#undef _Pre_opt_bytecount_c_
#undef _Pre_count_x_
#undef _Pre_opt_count_x_
#undef _Pre_bytecount_x_
#undef _Pre_opt_bytecount_x_
#undef _Pre_ptrdiff_count_
#undef _Pre_opt_ptrdiff_count_
#undef _Post_maybez_
#undef _Post_cap_
#undef _Post_bytecap_
#undef _Post_count_
#undef _Post_bytecount_
#undef _Post_count_c_
#undef _Post_bytecount_c_
#undef _Post_count_x_
#undef _Post_bytecount_x_
#undef _Post_z_count_
#undef _Post_z_bytecount_
#undef _Post_z_count_c_
#undef _Post_z_bytecount_c_
#undef _Post_z_count_x_
#undef _Post_z_bytecount_x_
#undef _Prepost_opt_z_
#undef _Prepost_count_
#undef _Prepost_opt_count_
#undef _Prepost_bytecount_
#undef _Prepost_opt_bytecount_
#undef _Prepost_count_c_
#undef _Prepost_opt_count_c_
#undef _Prepost_bytecount_c_
#undef _Prepost_opt_bytecount_c_
#undef _Prepost_count_x_
#undef _Prepost_opt_count_x_
#undef _Prepost_bytecount_x_
#undef _Prepost_opt_bytecount_x_
#undef _Prepost_valid_
#undef _Prepost_opt_valid_
#undef _Deref_prepost_z_
#undef _Deref_prepost_opt_z_
#undef _Deref_prepost_cap_
#undef _Deref_prepost_opt_cap_
#undef _Deref_prepost_bytecap_
#undef _Deref_prepost_opt_bytecap_
#undef _Deref_prepost_cap_x_
#undef _Deref_prepost_opt_cap_x_
#undef _Deref_prepost_bytecap_x_
#undef _Deref_prepost_opt_bytecap_x_
#undef _Deref_prepost_z_cap_
#undef _Deref_prepost_opt_z_cap_
#undef _Deref_prepost_z_bytecap_
#undef _Deref_prepost_opt_z_bytecap_
#undef _Deref_prepost_valid_cap_
#undef _Deref_prepost_opt_valid_cap_
#undef _Deref_prepost_valid_bytecap_
#undef _Deref_prepost_opt_valid_bytecap_
#undef _Deref_prepost_valid_cap_x_
#undef _Deref_prepost_opt_valid_cap_x_
#undef _Deref_prepost_valid_bytecap_x_
#undef _Deref_prepost_opt_valid_bytecap_x_
#undef _Deref_prepost_count_
#undef _Deref_prepost_opt_count_
#undef _Deref_prepost_bytecount_
#undef _Deref_prepost_opt_bytecount_
#undef _Deref_prepost_count_x_
#undef _Deref_prepost_opt_count_x_
#undef _Deref_prepost_bytecount_x_
#undef _Deref_prepost_opt_bytecount_x_
#undef _Deref_prepost_valid_
#undef _Deref_prepost_opt_valid_
#undef _Deref_out_z_cap_c_
#undef _Deref_inout_z_cap_c_
#undef _Deref_out_z_bytecap_c_
#undef _Deref_inout_z_bytecap_c_
#undef _Deref_inout_z_
#undef _Always_impl_
#undef _Bound_impl_
#undef _Field_range_impl_
#undef _Literal_impl_
#undef _Maybenull_impl_
#undef _Maybevalid_impl_
#undef _Must_inspect_impl_
#undef _Notliteral_impl_
#undef _Notnull_impl_
#undef _Notvalid_impl_
#undef _NullNull_terminated_impl_
#undef _Null_impl_
#undef _Null_terminated_impl_
#undef _Out_impl_
#undef _Out_opt_impl_
#undef _Points_to_data_impl_
#undef _Post_satisfies_impl_
#undef _Post_valid_impl_
#undef _Pre_satisfies_impl_
#undef _Pre_valid_impl_
#undef _Range_impl_
#undef _Readable_bytes_impl_
#undef _Readable_elements_impl_
#undef _Ret_valid_impl_
#undef _Satisfies_impl_
#undef _Valid_impl_
#undef _Writable_bytes_impl_
#undef _Writable_elements_impl_
#undef _In_range_impl_
#undef _Out_range_impl_
#undef _Ret_range_impl_
#undef _Deref_in_range_impl_
#undef _Deref_out_range_impl_
#undef _Deref_ret_range_impl_
#undef _Deref_pre_impl_
#undef _Deref_post_impl_
#undef __AuToQuOtE
#undef __deferTypecheck
#undef _SA_SPECSTRIZE
#undef _SAL_nop_impl_
#undef __nop_impl
#undef _SA_annotes0
#undef _SA_annotes1
#undef _SA_annotes2
#undef _SA_annotes3
#undef _Pre_impl_
#undef _Post_impl_
#undef _Deref_impl_
#undef _Notref_impl_
#undef __ANNOTATION
#undef __PRIMOP
#undef __QUALIFIER
#undef __In_impl_
#undef _SA_annotes0
#undef _SA_annotes1
#undef _SA_annotes2
#undef _SA_annotes3
#undef _Pre_impl_
#undef _Post_impl_
#undef _Deref_impl_
#undef _Notref_impl_
#undef __ANNOTATION
#undef __PRIMOP
#undef __QUALIFIER
#undef __In_impl_
#undef _SA_annotes0
#undef _SA_annotes1
#undef _SA_annotes2
#undef _SA_annotes3
#undef __ANNOTATION
#undef __PRIMOP
#undef __QUALIFIER
#undef _Check_return_impl_
#undef _Success_impl_
#undef _On_failure_impl_
#undef _Printf_format_string_impl_
#undef _Scanf_format_string_impl_
#undef _Scanf_s_format_string_impl_
#undef _In_bound_impl_
#undef _Out_bound_impl_
#undef _Ret_bound_impl_
#undef _Deref_in_bound_impl_
#undef _Deref_out_bound_impl_
#undef _Deref_ret_bound_impl_
#undef __valid_impl
#undef __maybevalid_impl
#undef __notvalid_impl
#undef __null_impl
#undef __maybenull_impl
#undef __notnull_impl
#undef __null_impl_notref
#undef __maybenull_impl_notref
#undef __notnull_impl_notref
#undef __zterm_impl
#undef __maybezterm_impl
#undef __maybzterm_impl
#undef __notzterm_impl
#undef __readaccess_impl
#undef __writeaccess_impl
#undef __allaccess_impl
#undef __readaccess_impl_notref
#undef __writeaccess_impl_notref
#undef __allaccess_impl_notref
#undef __cap_impl
#undef __bytecap_impl
#undef __bytecount_impl
#undef __count_impl
#undef __cap_impl
#undef __bytecap_impl
#undef __bytecount_impl
#undef __count_impl
#undef __cap_c_impl
#undef __cap_c_one_notref_impl
#undef __cap_for_impl
#undef __cap_x_impl
#undef __bytecap_c_impl
#undef __bytecap_x_impl
#undef __mult_impl
#undef __count_c_impl
#undef __count_x_impl
#undef __bytecount_c_impl
#undef __bytecount_x_impl
#undef _At_impl_
#undef _At_buffer_impl_
#undef _When_impl_
#undef _Group_impl_
#undef _GrouP_impl_
#undef _Use_decl_anno_impl_
#undef _Pre1_impl_
#undef _Pre2_impl_
#undef _Pre3_impl_
#undef _Post1_impl_
#undef _Post2_impl_
#undef _Post3_impl_
#undef _Ret1_impl_
#undef _Ret2_impl_
#undef _Ret3_impl_
#undef _Deref_pre1_impl_
#undef _Deref_pre2_impl_
#undef _Deref_pre3_impl_
#undef _Deref_post1_impl_
#undef _Deref_post2_impl_
#undef _Deref_post3_impl_
#undef _Deref_ret1_impl_
#undef _Deref_ret2_impl_
#undef _Deref_ret3_impl_
#undef _Deref2_pre1_impl_
#undef _Deref2_post1_impl_
#undef _Deref2_ret1_impl_
#undef __inner_typefix
#undef __inner_exceptthat
#undef _Check_return_impl_
#undef _Success_impl_
#undef _On_failure_impl_
#undef _Printf_format_string_impl_
#undef _Scanf_format_string_impl_
#undef _Scanf_s_format_string_impl_
#undef _In_bound_impl_
#undef _Out_bound_impl_
#undef _Ret_bound_impl_
#undef _Deref_in_bound_impl_
#undef _Deref_out_bound_impl_
#undef _Deref_ret_bound_impl_
#undef __null_impl
#undef __notnull_impl
#undef __maybenull_impl
#undef __valid_impl
#undef __notvalid_impl
#undef __maybevalid_impl
#undef __null_impl_notref
#undef __maybenull_impl_notref
#undef __notnull_impl_notref
#undef __zterm_impl
#undef __maybezterm_impl
#undef __maybzterm_impl
#undef __notzterm_impl
#undef __readaccess_impl
#undef __writeaccess_impl
#undef __allaccess_impl
#undef __readaccess_impl_notref
#undef __writeaccess_impl_notref
#undef __allaccess_impl_notref
#undef __cap_impl
#undef __cap_c_impl
#undef __cap_c_one_notref_impl
#undef __cap_for_impl
#undef __cap_x_impl
#undef __bytecap_impl
#undef __bytecap_c_impl
#undef __bytecap_x_impl
#undef __mult_impl
#undef __count_impl
#undef __count_c_impl
#undef __count_x_impl
#undef __bytecount_impl
#undef __bytecount_c_impl
#undef __bytecount_x_impl
#undef _At_impl_
#undef _At_buffer_impl_
#undef _Group_impl_
#undef _GrouP_impl_
#undef _When_impl_
#undef _Use_decl_anno_impl_
#undef _Pre1_impl_
#undef _Pre2_impl_
#undef _Pre3_impl_
#undef _Post1_impl_
#undef _Post2_impl_
#undef _Post3_impl_
#undef _Ret1_impl_
#undef _Ret2_impl_
#undef _Ret3_impl_
#undef _Deref_pre1_impl_
#undef _Deref_pre2_impl_
#undef _Deref_pre3_impl_
#undef _Deref_post1_impl_
#undef _Deref_post2_impl_
#undef _Deref_post3_impl_
#undef _Deref_ret1_impl_
#undef _Deref_ret2_impl_
#undef _Deref_ret3_impl_
#undef _Deref2_pre1_impl_
#undef _Deref2_post1_impl_
#undef _Deref2_ret1_impl_
#undef __inner_typefix
#undef __inner_exceptthat
#undef SA
#undef REPEATABLE
#undef SA
#undef REPEATABLE
#undef _SAL_nop_impl_
#undef _At_impl_
#undef _At_buffer_impl_
#undef _When_impl_
#undef _Group_impl_
#undef _GrouP_impl_
#undef _Use_decl_anno_impl_
#undef _Points_to_data_impl_
#undef _Literal_impl_
#undef _Notliteral_impl_
#undef _Pre_valid_impl_
#undef _Post_valid_impl_
#undef _Ret_valid_impl_
#undef _Check_return_impl_
#undef _Must_inspect_impl_
#undef _Success_impl_
#undef _On_failure_impl_
#undef _Always_impl_
#undef _Printf_format_string_impl_
#undef _Scanf_format_string_impl_
#undef _Scanf_s_format_string_impl_
#undef _Raises_SEH_exception_impl_
#undef _Maybe_raises_SEH_exception_impl_
#undef _In_bound_impl_
#undef _Out_bound_impl_
#undef _Ret_bound_impl_
#undef _Deref_in_bound_impl_
#undef _Deref_out_bound_impl_
#undef _Deref_ret_bound_impl_
#undef _Range_impl_
#undef _In_range_impl_
#undef _Out_range_impl_
#undef _Ret_range_impl_
#undef _Deref_in_range_impl_
#undef _Deref_out_range_impl_
#undef _Deref_ret_range_impl_
#undef _Field_range_impl_
#undef _Pre_satisfies_impl_
#undef _Post_satisfies_impl_
#undef _Satisfies_impl_
#undef _Null_impl_
#undef _Notnull_impl_
#undef _Maybenull_impl_
#undef _Valid_impl_
#undef _Notvalid_impl_
#undef _Maybevalid_impl_
#undef _Readable_bytes_impl_
#undef _Readable_elements_impl_
#undef _Writable_bytes_impl_
#undef _Writable_elements_impl_
#undef _Null_terminated_impl_
#undef _NullNull_terminated_impl_
#undef _Pre_impl_
#undef _Pre1_impl_
#undef _Pre2_impl_
#undef _Pre3_impl_
#undef _Post_impl_
#undef _Post1_impl_
#undef _Post2_impl_
#undef _Post3_impl_
#undef _Ret1_impl_
#undef _Ret2_impl_
#undef _Ret3_impl_
#undef _Deref_pre1_impl_
#undef _Deref_pre2_impl_
#undef _Deref_pre3_impl_
#undef _Deref_post1_impl_
#undef _Deref_post2_impl_
#undef _Deref_post3_impl_
#undef _Deref_ret1_impl_
#undef _Deref_ret2_impl_
#undef _Deref_ret3_impl_
#undef _Deref2_pre1_impl_
#undef _Deref2_post1_impl_
#undef _Deref2_ret1_impl_
#undef _SAL_nop_impl_
#undef _At_impl_
#undef _When_impl_
#undef _Group_impl_
#undef _GrouP_impl_
#undef _At_buffer_impl_
#undef _Use_decl_anno_impl_
#undef _Points_to_data_impl_
#undef _Literal_impl_
#undef _Notliteral_impl_
#undef _Notref_impl_
#undef _Pre_valid_impl_
#undef _Post_valid_impl_
#undef _Ret_valid_impl_
#undef _Check_return_impl_
#undef _Must_inspect_impl_
#undef _Success_impl_
#undef _On_failure_impl_
#undef _Always_impl_
#undef _Printf_format_string_impl_
#undef _Scanf_format_string_impl_
#undef _Scanf_s_format_string_impl_
#undef _In_bound_impl_
#undef _Out_bound_impl_
#undef _Ret_bound_impl_
#undef _Deref_in_bound_impl_
#undef _Deref_out_bound_impl_
#undef _Deref_ret_bound_impl_
#undef _Range_impl_
#undef _In_range_impl_
#undef _Out_range_impl_
#undef _Ret_range_impl_
#undef _Deref_in_range_impl_
#undef _Deref_out_range_impl_
#undef _Deref_ret_range_impl_
#undef _Satisfies_impl_
#undef _Pre_satisfies_impl_
#undef _Post_satisfies_impl_
#undef _Null_impl_
#undef _Notnull_impl_
#undef _Maybenull_impl_
#undef _Valid_impl_
#undef _Notvalid_impl_
#undef _Maybevalid_impl_
#undef _Field_range_impl_
#undef _Pre_impl_
#undef _Pre1_impl_
#undef _Pre2_impl_
#undef _Pre3_impl_
#undef _Post_impl_
#undef _Post1_impl_
#undef _Post2_impl_
#undef _Post3_impl_
#undef _Ret1_impl_
#undef _Ret2_impl_
#undef _Ret3_impl_
#undef _Deref_pre1_impl_
#undef _Deref_pre2_impl_
#undef _Deref_pre3_impl_
#undef _Deref_post1_impl_
#undef _Deref_post2_impl_
#undef _Deref_post3_impl_
#undef _Deref_ret1_impl_
#undef _Deref_ret2_impl_
#undef _Deref_ret3_impl_
#undef _Deref2_pre1_impl_
#undef _Deref2_post1_impl_
#undef _Deref2_ret1_impl_
#undef _Readable_bytes_impl_
#undef _Readable_elements_impl_
#undef _Writable_bytes_impl_
#undef _Writable_elements_impl_
#undef _Null_terminated_impl_
#undef _NullNull_terminated_impl_
#undef __inner_typefix
#undef __inner_exceptthat
#undef __specstrings
    #undef _SA_SPECSTRIZE
    #undef __null
    #undef __notnull
    #undef __maybenull
    #undef __readonly
    #undef __notreadonly
    #undef __maybereadonly
    #undef __valid
    #undef __notvalid
    #undef __maybevalid
    #undef __readableTo
    #undef __elem_readableTo
    #undef __byte_readableTo
    #undef __writableTo
    #undef __elem_writableTo
    #undef __byte_writableTo
    #undef __deref
    #undef __pre
    #undef __post
    #undef __precond
    #undef __postcond
    #undef __exceptthat
    #undef __refparam
    #undef __inner_control_entrypoint
    #undef __inner_data_entrypoint
    #undef __inner_override
    #undef __inner_callback
    #undef __inner_blocksOn
    #undef __inner_fallthrough_dec
    #undef __inner_fallthrough
    #undef __post_except_maybenull
    #undef __pre_except_maybenull
    #undef __post_deref_except_maybenull
    #undef __pre_deref_except_maybenull
    #undef __inexpressible_readableTo
    #undef __inexpressible_writableTo
    #undef __null
    #undef __notnull
    #undef __maybenull
    #undef __readonly
    #undef __notreadonly
    #undef __maybereadonly
    #undef __valid
    #undef __notvalid
    #undef __maybevalid
    #undef __readableTo
    #undef __elem_readableTo
    #undef __byte_readableTo
    #undef __writableTo
    #undef __elem_writableTo
    #undef __byte_writableTo
    #undef __deref
    #undef __pre
    #undef __post
    #undef __precond
    #undef __postcond
    #undef __exceptthat
    #undef __inner_override
    #undef __inner_callback
    #undef __inner_blocksOn
    #undef __inner_fallthrough_dec
    #undef __inner_fallthrough
    #undef __refparam
    #undef __inner_control_entrypoint
    #undef __inner_data_entrypoint
    #undef __post_except_maybenull
    #undef __pre_except_maybenull
    #undef __post_deref_except_maybenull
    #undef __pre_deref_except_maybenull
    #undef __inexpressible_readableTo
    #undef __inexpressible_writableTo
#undef __in
#undef __out
#undef __ecount
#undef __bcount
#undef __in_ecount
#undef __in_bcount
#undef __in_z
#undef __in_ecount_z
#undef __in_bcount_z
#undef __in_nz
#undef __in_ecount_nz
#undef __in_bcount_nz
#undef __out_ecount
#undef __out_bcount
#undef __out_ecount_part
#undef __out_bcount_part
#undef __out_ecount_full
#undef __out_bcount_full
#undef __out_z
#undef __out_z_opt
#undef __out_ecount_z
#undef __out_bcount_z
#undef __out_ecount_part_z
#undef __out_bcount_part_z
#undef __out_ecount_full_z
#undef __out_bcount_full_z
#undef __out_nz
#undef __out_nz_opt
#undef __out_ecount_nz
#undef __out_bcount_nz
#undef __inout
#undef __inout_ecount
#undef __inout_bcount
#undef __inout_ecount_part
#undef __inout_bcount_part
#undef __inout_ecount_full
#undef __inout_bcount_full
#undef __inout_z
#undef __inout_ecount_z
#undef __inout_bcount_z
#undef __inout_nz
#undef __inout_ecount_nz
#undef __inout_bcount_nz
#undef __ecount_opt
#undef __bcount_opt
#undef __in_opt
#undef __in_ecount_opt
#undef __in_bcount_opt
#undef __in_z_opt
#undef __in_ecount_z_opt
#undef __in_bcount_z_opt
#undef __in_nz_opt
#undef __in_ecount_nz_opt
#undef __in_bcount_nz_opt
#undef __out_opt
#undef __out_ecount_opt
#undef __out_bcount_opt
#undef __out_ecount_part_opt
#undef __out_bcount_part_opt
#undef __out_ecount_full_opt
#undef __out_bcount_full_opt
#undef __out_ecount_z_opt
#undef __out_bcount_z_opt
#undef __out_ecount_part_z_opt
#undef __out_bcount_part_z_opt
#undef __out_ecount_full_z_opt
#undef __out_bcount_full_z_opt
#undef __out_ecount_nz_opt
#undef __out_bcount_nz_opt
#undef __inout_opt
#undef __inout_ecount_opt
#undef __inout_bcount_opt
#undef __inout_ecount_part_opt
#undef __inout_bcount_part_opt
#undef __inout_ecount_full_opt
#undef __inout_bcount_full_opt
#undef __inout_z_opt
#undef __inout_ecount_z_opt
#undef __inout_ecount_z_opt
#undef __inout_bcount_z_opt
#undef __inout_nz_opt
#undef __inout_ecount_nz_opt
#undef __inout_bcount_nz_opt
#undef __deref_ecount
#undef __deref_bcount
#undef __deref_out
#undef __deref_out_ecount
#undef __deref_out_bcount
#undef __deref_out_ecount_part
#undef __deref_out_bcount_part
#undef __deref_out_ecount_full
#undef __deref_out_bcount_full
#undef __deref_out_z
#undef __deref_out_ecount_z
#undef __deref_out_bcount_z
#undef __deref_out_nz
#undef __deref_out_ecount_nz
#undef __deref_out_bcount_nz
#undef __deref_inout
#undef __deref_inout_z
#undef __deref_inout_ecount
#undef __deref_inout_bcount
#undef __deref_inout_ecount_part
#undef __deref_inout_bcount_part
#undef __deref_inout_ecount_full
#undef __deref_inout_bcount_full
#undef __deref_inout_ecount_z
#undef __deref_inout_bcount_z
#undef __deref_inout_nz
#undef __deref_inout_ecount_nz
#undef __deref_inout_bcount_nz
#undef __deref_ecount_opt
#undef __deref_bcount_opt
#undef __deref_out_opt
#undef __deref_out_ecount_opt
#undef __deref_out_bcount_opt
#undef __deref_out_ecount_part_opt
#undef __deref_out_bcount_part_opt
#undef __deref_out_ecount_full_opt
#undef __deref_out_bcount_full_opt
#undef __deref_out_z_opt
#undef __deref_out_ecount_z_opt
#undef __deref_out_bcount_z_opt
#undef __deref_out_nz_opt
#undef __deref_out_ecount_nz_opt
#undef __deref_out_bcount_nz_opt
#undef __deref_inout_opt
#undef __deref_inout_ecount_opt
#undef __deref_inout_bcount_opt
#undef __deref_inout_ecount_part_opt
#undef __deref_inout_bcount_part_opt
#undef __deref_inout_ecount_full_opt
#undef __deref_inout_bcount_full_opt
#undef __deref_inout_z_opt
#undef __deref_inout_ecount_z_opt
#undef __deref_inout_bcount_z_opt
#undef __deref_inout_nz_opt
#undef __deref_inout_ecount_nz_opt
#undef __deref_inout_bcount_nz_opt
#undef __deref_opt_ecount
#undef __deref_opt_bcount
#undef __deref_opt_out
#undef __deref_opt_out_z
#undef __deref_opt_out_ecount
#undef __deref_opt_out_bcount
#undef __deref_opt_out_ecount_part
#undef __deref_opt_out_bcount_part
#undef __deref_opt_out_ecount_full
#undef __deref_opt_out_bcount_full
#undef __deref_opt_inout
#undef __deref_opt_inout_ecount
#undef __deref_opt_inout_bcount
#undef __deref_opt_inout_ecount_part
#undef __deref_opt_inout_bcount_part
#undef __deref_opt_inout_ecount_full
#undef __deref_opt_inout_bcount_full
#undef __deref_opt_inout_z
#undef __deref_opt_inout_ecount_z
#undef __deref_opt_inout_bcount_z
#undef __deref_opt_inout_nz
#undef __deref_opt_inout_ecount_nz
#undef __deref_opt_inout_bcount_nz
#undef __deref_opt_ecount_opt
#undef __deref_opt_bcount_opt
#undef __deref_opt_out_opt
#undef __deref_opt_out_ecount_opt
#undef __deref_opt_out_bcount_opt
#undef __deref_opt_out_ecount_part_opt
#undef __deref_opt_out_bcount_part_opt
#undef __deref_opt_out_ecount_full_opt
#undef __deref_opt_out_bcount_full_opt
#undef __deref_opt_out_z_opt
#undef __deref_opt_out_ecount_z_opt
#undef __deref_opt_out_bcount_z_opt
#undef __deref_opt_out_nz_opt
#undef __deref_opt_out_ecount_nz_opt
#undef __deref_opt_out_bcount_nz_opt
#undef __deref_opt_inout_opt
#undef __deref_opt_inout_ecount_opt
#undef __deref_opt_inout_bcount_opt
#undef __deref_opt_inout_ecount_part_opt
#undef __deref_opt_inout_bcount_part_opt
#undef __deref_opt_inout_ecount_full_opt
#undef __deref_opt_inout_bcount_full_opt
#undef __deref_opt_inout_z_opt
#undef __deref_opt_inout_ecount_z_opt
#undef __deref_opt_inout_bcount_z_opt
#undef __deref_opt_inout_nz_opt
#undef __deref_opt_inout_ecount_nz_opt
#undef __deref_opt_inout_bcount_nz_opt
#undef __success
#undef __nullterminated
#undef __nullnullterminated
#undef __clr_reserved
#undef __checkReturn
#undef __typefix
#undef __override
#undef __callback
#undef __format_string
#undef __blocksOn
#undef __control_entrypoint
#undef __data_entrypoint
#undef __useHeader
#undef __on_failure
    #undef __fallthrough
#undef __analysis_assume
#undef __analysis_assume
#undef _Analysis_assume_
#undef _Analysis_assume_
#undef _Analysis_noreturn_
#undef _Analysis_assume_nullterminated_
#undef _Analysis_assume_nullterminated_
#undef ___MKID
#undef __MKID
#undef __GENSYM
#undef _Analysis_mode_impl_
#undef _Analysis_mode_
#undef _In_function_class_
#undef _Function_class_
//#undef _Interlocked_operand_
#undef _Enum_is_bitflag_
#undef _Strict_type_match_
#undef _Maybe_raises_SEH_exception_
#undef _Raises_SEH_exception_
#undef _Interlocked_operand_
